### PR TITLE
Server-side code added (node) and How2Contribute.md file added. Updated README.md

### PR DESCRIPTION
**Pull request by cfleur**
Server code is not functioning to respond with the style sheets and html files correctly. 
Perhaps we need to transform them into .ejs files?
But thought you would like to play with it too...
Also all the node modules are in .gitignore file.
Also I have opened up some issues, hope they transfer over.

If you're wondering about media files, they were the videos from the pitch. Git has a 100Mb size restriction. Had to rebase and do a bunch of stuff to get rid of them, so the conflict fixing stuff was from that. Don't worry its fixed now!

Page is published from my repo here: https://cfleur.github.io/residentialyardgame/

~^.^~

### CODE REVIEW

**Review by SSSvensk — APPROVED** [review]
Merged. Definitely need to do something to original HTML/CSS-files, cos they werent not written for Node purposes...
(Issues doesn't seem to transfer into my repo:( But so far they seem to be quite familiar:))

**Comment by SSSvensk** [comment]
I managed to get some CSS-files working routing them in server.js like this:
`app.get("/css/styles.css", function(req,res){`
`	res.sendFile(__dirname + '/css/styles.css');`
`})`

`app.get("/css/mapscss.css", function(req,res){`
`	res.sendFile(__dirname + '/css/mapscss.css');`
`})`

Overall HTML and CSS-files are quite messy, maybe need to think about re-arranging them or exploding and re-creating the whole UI. This would actually help to responsiveness and also make the HTML-documents clearer...

**Comment by cfleur** [comment]
Awesome! I will look at it on the weekend. About the HTML-CSS-mess I totally agree I was thinking the same thing. ...Bootstrap??

**Comment by SSSvensk** [comment]
Bootstrap would be cool and useful. Maybe we can just remove all the images except the `Ihan Pihalla` logo and replace them with HTML-elements.

(These over 1000 line CSS-files are ridicilous)

**Pull request merged**
